# Smart Intercom project
# https://github.com/Anonym-tsk/smart-domofon/tree/master/ge1mer

############# User configuration #############

substitutions:
  # Build configuration
  board_name: "Domofon"
  mdns_name: "domofon"
  build_path: "domofon/"

  # Relays configuration
  phone_relay_inverted: 'true'  # Set to 'false' if you have NO phone relay

  # Wifi credentials
  wifi_ssid: "-----"
  wifi_password: ""
  ap_ssid: "domofon"
  ap_password: "1234567890"

  # MQTT credentials
  mqtt_host: "10.0.0.1"
  mqtt_port: "1883"
  mqtt_username: ""
  mqtt_password: ""



  # Software configuration
  call_start_detect_delay: 50ms     # Wait a while before going into a ring state
  call_end_detect_delay: 4000ms     # Interval between rings to detect incoming call
  short_click_time_from: 50ms       # Short button click min time
  short_click_time_to: 1000ms       # Long button click min time

########### End user configuration ###########

packages:
  base: github://bobrik-spb/domofon/esphome/packages/base.yaml@main
  api: github://bobrik-spb/domofon/esphome/packages/api.yaml@main
  #mqtt: github://bobrik-spb/domofon/esphome/packages/mqtt.yaml@main
  #web_server: ggithub://bobrik-spb/domofon/esphome/packages/web_server.yaml@master
  captive_portal: github://bobrik-spb/domofon/esphome/packages/captive_portal.yaml@main

